build:
  image: golang:1.5
  environment:
    - GO15VENDOREXPERIMENT=1
  commands:
    - sleep 10
    - go get -v ./...
    - go test -v -cover ./...

compose:
  database:
    image: mysql:5.6.27
    environment:
      - MYSQL_DATABASE=todo
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes    
